server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bootcamp_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  sql:
    init:
      mode: always

webclient:
  capacity: ${WEBCLIENT_CAPACITY:http://localhost:8083/api/v1/capacity/bootcamp-capacities}

allowed-origins: ${ALLOWED_ORIGIN:http://localhost:4200}

appDescription: "Pragma Reactive Bootcamp"
appVersion: "1.0.0"
